### ISSUE TITLE
[Bug] Wipe folder doesn't works.

### ISSUE THREAD

**Issue by partrita** [DrewThomasson/ebook_to_audiobook_styletts#3]
I believe there is bug in `styletts_to_ebook.py` script. Which is

```python
if is_folder_empty == False:
```

It should be like this

```python
if is_folder_empty(output_audio_directory) is False:
```

Thanks

**Comment by DrewThomasson** [comment]
Is that fix I included in your merge you requested?

**Comment by DrewThomasson** [comment]
Merged your suggestion code!
